# Generated by Django 5.2 on 2025-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10, null=True),
        ),
    ]
